#!/bin/sh
# firewall            Start iptables firewall

. /lib/lsb/init-functions
. /etc/firewall/firewall.conf

purge() {
    log_action_msg "Purging and allowing all traffic"
    iptables -P OUTPUT ACCEPT
    iptables -P FORWARD ACCEPT
    iptables -P INPUT ACCEPT
    iptables -F
    iptables -X
}

setup() {
    log_action_msg "Setting default policies to DROP"
    # Keep connection already open
    iptables -A INPUT  -m state --state RELATED,ESTABLISHED -j ACCEPT
    iptables -A OUTPUT -m state --state RELATED,ESTABLISHED -j ACCEPT

    # Bloc all traffic
    iptables -P INPUT DROP
    iptables -P FORWARD DROP
    iptables -P OUTPUT DROP

    # Authorise loopback
    iptables -A INPUT  -i lo -j ACCEPT
    iptables -A OUTPUT -o lo -j ACCEPT

    # Authorise DNS request
    if [ -n "$ENABLE_DNS" ] && [ "$ENABLE_DNS" = "true" ]; then
        iptables -A INPUT  -s $DNS -p udp --sport 53 -m state --state ESTABLISHED,RELATED -j ACCEPT
        iptables -A OUTPUT -d $DNS -p udp --dport 53 -m state --state NEW,ESTABLISHED     -j ACCEPT
    fi

    # ICMP (Ping)
    iptables -A INPUT  -p icmp -j ACCEPT
    iptables -A OUTPUT -p icmp -j ACCEPT

    for port in $TCPPORTS ; do
        log_action_msg "Allowing access to tcp port $port"
        iptables -A INPUT  -p tcp --dport $port -j ACCEPT
        iptables -A OUTPUT -p tcp --dport $port -j ACCEPT
    done

    for port in $UDPPORTS ; do
        log_action_msg "Allowing access to udp port $port"
        iptables -A INPUT  -p udp --dport $port -j ACCEPT
        iptables -A OUTPUT -p udp --dport $port -j ACCEPT
    done
}

case "$1" in
    start)
        log_daemon_msg "Starting firewall..." $DAEMON
        log_end_msg 0
        purge
        setup
        ;;
    stop)
        log_daemon_msg "Stopping firewall..." $DAEMON
        log_end_msg 0
        purge
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    status)
        iptables -n -L
        ;;
    *)
        log_action_msg "Usage: $0 {start|stop|restart|status}"
        ;;
esac
